---

version: 1.0.{build}

os:
  - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0

before_build:
  - cmd: mkdir build
  - cmd: cd build

build_script:
  - cmd: cmake .. -DEENABLE_TESTING=ON
  - cmd: cmake --build . --config $(configuration)

test_script:
  - cmd: ctest -VV
