---

engines:
  duplication:
    enabled: true
    config:
      languages:
        - python
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  pep8:
    enabled: true
ratings:
  paths:
    - "**"
exclude_paths:
  - "thirdparty/"
